# Generated by Django 3.2.16 on 2023-09-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230912_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsofrecipe',
            options={'verbose_name': ('Ингредиент рецепта',), 'verbose_name_plural': ('Ингредиенты рецепта',)},
        ),
    ]
