# Generated by Django 3.2.16 on 2023-09-26 10:32

from django.db import migrations, models
import recipes.validator


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230912_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsofrecipe',
            options={'verbose_name': ('Ингредиент рецепта',), 'verbose_name_plural': ('Ингредиенты рецепта',)},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[recipes.validator.validator_more_one], verbose_name='Время приготовления'),
        ),
    ]
